import streamlit as st
import pandas as pd
import plotly.express as px
from fpdf import FPDF
import io

from agents import get_or_create_agents


def build_report_text(
    business_user,
    analyst_agent,
    knowledge_agent,
    eda_summary,
    model_metrics,
    predictions,
    chart_paths,
):
    """
    Use the agentic architecture to assemble a narrative business report.
    BusinessUser delegates to AIAnalystAgent and KnowledgeAgent for insights.
    """
    # Core narrative generated by the agents (LLM lives inside KnowledgeAgent)
    agent_insights = business_user.downloadReport(analyst_agent, knowledge_agent)

    charts_text = (
        "\n".join([f"[Chart file] {p}" for p in chart_paths]) if chart_paths else "No charts."
    )

    sections = [
        "# Business Report",
        "",
        "## Exploratory Data Analysis Summary",
        str(eda_summary),
        "",
        "## Model Metrics",
        str(model_metrics),
        "",
        "## Predictions",
        str(predictions),
        "",
        "## Agent Insights",
        agent_insights,
        "",
        "## Charts",
        charts_text,
    ]

    return "\n".join(sections)


# ----------------- PDF Export Function -----------------
def export_to_pdf(report_text, chart_paths=[]):
    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("Arial", size=12)
    
    # Add text
    for line in report_text.split("\n"):
        pdf.multi_cell(0, 8, line)
    
    # Add charts
    y_position = pdf.get_y() + 10
    for chart in chart_paths:
        try:
            pdf.image(chart, x=10, y=y_position, w=180)
            y_position += 100
        except:
            pass
    
    pdf_output = "business_report.pdf"
    pdf.output(pdf_output)
    with open(pdf_output, "rb") as f:
        pdf_bytes = f.read()
    return pdf_bytes

# ----------------- Streamlit Show Function -----------------
def show():
    st.subheader("📄 Business Report Generation")
    st.markdown(
        "Generate a comprehensive business report using the agentic architecture "
        "(BusinessUser → AIAnalystAgent → KnowledgeAgent)."
    )

    # Check if necessary data exists
    if "dataset" not in st.session_state:
        st.warning("Upload a dataset on the Home page first.")
        return
    if "ml_results" not in st.session_state:
        st.warning("Train a model first on the ML Training page.")
        return

    # Initialize and sync agents with current session data
    business_user, analyst_agent, knowledge_agent = get_or_create_agents(st.session_state)

    df = st.session_state["dataset"]
    analyst_agent.dataset = df
    business_user.uploaded_dataset = df

    ml_results = st.session_state.get("ml_results", {})
    analyst_agent.analysis_results["ml"] = ml_results
    predictions = st.session_state.get("predictions", None)

    # Optional: User can write EDA summary manually or use placeholder
    eda_default = "Dataset contains basic statistics, missing values, and feature distributions."
    if "eda_results" in st.session_state:
        eda_default = str(st.session_state["eda_results"])

    eda_summary = st.text_area(
        "EDA Summary (you can edit this):",
        value=eda_default,
    )

    model_metrics = st.text_area(
        "Model Metrics (you can edit this):",
        value=str(ml_results),
    )

    # Generate simple charts
    chart_paths = []
    numeric_cols = df.select_dtypes(include="number").columns.tolist()
    if numeric_cols:
        for col in numeric_cols[:2]:  # Take first 2 numeric columns as example
            fig = px.histogram(df, x=col, title=f"{col} Distribution")
            chart_file = f"chart_{col}.png"
            fig.write_image(chart_file)
            chart_paths.append(chart_file)

    if st.button("Generate Report"):
        with st.spinner("Generating report using the agents..."):
            predictions_text = str(predictions)

            report_text = build_report_text(
                business_user=business_user,
                analyst_agent=analyst_agent,
                knowledge_agent=knowledge_agent,
                eda_summary=eda_summary,
                model_metrics=model_metrics,
                predictions=predictions_text,
                chart_paths=chart_paths,
            )

            st.success("✅ Report Generated!")
            st.text_area("Generated Report:", value=report_text, height=400)

            # ----------------- Download Buttons -----------------
            # PDF
            pdf_bytes = export_to_pdf(report_text, chart_paths)
            st.download_button(
                label="Download Report as PDF",
                data=pdf_bytes,
                file_name="business_report.pdf",
                mime="application/pdf",
            )

            # HTML
            st.download_button(
                label="Download Report as HTML",
                data=report_text.encode(),
                file_name="business_report.html",
                mime="text/html",
            )

